# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metaball_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12metaball_msg.proto\x12\x08MetaBall\"U\n\x08MetaBall\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0b\n\x03img\x18\x02 \x01(\x0c\x12\x0c\n\x04pose\x18\x03 \x03(\x01\x12\r\n\x05\x66orce\x18\x04 \x03(\x01\x12\x0c\n\x04node\x18\x05 \x03(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metaball_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METABALL._serialized_start=32
  _METABALL._serialized_end=117
# @@protoc_insertion_point(module_scope)
